### ISSUE TITLE
Elementor Pro + Addon support

### ISSUE THREAD

**Issue by patrickposner** [Simply-Static/simply-static#106]
Following up on issue #80 there are a couple of things we need to cover:

### 1) Elementor Pro

We should also replicate what we are doing with Elementor for Elementor Pro.
If Elementor Pro is installed, some of the bundled files are placed in /wp-content/plugins/elementor-pro/assets/.

### 2) Lottie Files

It seems that the JSON files for Lottie animations are added somewhere else in wp-content/uploads/
Lottie is a widget coming from Elementor Pro - we should auto-include the directory (if there is a default one).

**Comment by obuylov** [comment]
Hello guys,
I also ran into a problem when using this widget:: https://ultimateelementor.com/widgets/video/
I have to manually change the structure of relative URLs to MP4 files after export in order for the video to work.

**Comment by igorbenic** [comment]
Hi @obuylov, can you explain how do you have to change the structure when it's set to relative? What URL do you get when it's exported and what do you have to change it to? 

I don't have a license to that plugin so can't test it directly. But getting this answer might help us get the idea of how to approach it.

**Comment by snap360-zach** [comment]
Not to necromancer a closed issue -> we had to add an action to ss_after_extract_and_replace_urls_in_html (ss_match_tags changes didnt get us 100% but got close)  to parse the data-settings attribute json on divs for the background_slideshow_gallery and a few other keys to get a full integration going with elementor pro, otherwise images that it places in slider backgrounds etc would be missing. There was probably a better way but figured I would share my experience in-case anyone else ran into the issue. Sorry if its not the right place

**Comment by snap360-zach** [comment]
There seems to be an issue with the integration and Simply Static Pro's publish single for pages that are elementor and have been previously generated ( may also occur on single publish of new can test further)  -> none of the page specific elementor css files are added to the export by default. 

Steps to reproduce:
Make an elementor page
Export it using a full site build 
Edit the page
Export it using the publish static button that pro adds
Static export is made, elementor css is left out of date since it wasn't fetched

I can open a new issue for this but didn't want to start opening Pro issues randomly and figured this might be the best place to mention it.  We ended up working around the issue by adding an action to ss_get_option_additional_files and checking the value of the simply-static-use-single option and if it was set just forcing in the css with the extra files. Again probably a better way todo it but figured id mention it to try and save anyone from the head-scratching few minutes I had. Sorry if any of the issue reporting sounds negative, not my intention the work is great!
