### ISSUE TITLE
Static export removes code for Photoswipe Gallery

### ISSUE THREAD

**Issue by anthonykasabian** [Simply-Static/simply-static#152]
Hy and thanks for this great piece of software. Im running into a little trouble while working on my site.
After export some parts of my markup are gone and it makes no sense to me why this is happening but maybe we could tackle this issue down.

First here's the part coming from the template rendered (BASIC Wp running with local):
![Screenshot 2023-06-09 at 15 16 49](https://github.com/Simply-Static/simply-static/assets/12294102/bed6313f-7769-422b-a26b-68b14b35431b)

And that's after the export:
![Screenshot 2023-06-09 at 15 18 19](https://github.com/Simply-Static/simply-static/assets/12294102/cae5148e-e839-4b7f-b59d-821323c6785f)

Thanks for help and so on, have a nice day and greetings from Berlin

**Comment by patrickposner** [comment]
Hey @anthonykasabian,

thanks for reaching out!

While we can't really do technical support here specifically for another plugin, I would assume it's because the markup for Photoswipe is added dynamically to the DOM (maybe it makes use of lazy loading only to be included once the visitor reaches a certain point of the page?)

As we don't have something like a headless browser for doing the crawling process, Simply Static will not wait for each interaction happening on the page. Instead, it will parse only what's visible on the initial page load.
