### ISSUE TITLE
AWS S3 Zip file deployments

### ISSUE THREAD

**Issue by oc-christopher-billett** [Simply-Static/simply-static#163]
The AWS S3 feature although great can take some time to upload. I've experienced in excess of 1.5hrs for a full site.

What's the possibility of having the S3 feature with an option upload a zipped version so we could look to uncompress using lambda to reduce the overall deployment times to something more feasible?

**Comment by patrickposner** [comment]
Hey @oc-christopher-billett,

good point!

We do have an even better way to handle that without requiring a lambda function.

With the next update, our AWS integration will use "transfer" instead of recursively transferring files (which is up to 70% faster).

I will close that issue here as it relates to the pro version, but feel free to reach out if you have any further suggestions!
