### ISSUE TITLE
Issue Replacing URLs For Offline Usage

### ISSUE THREAD

**Issue by sr293** [Simply-Static/simply-static#208]
An issue is occurring while replacing urls for offline usage. During export, it will prematurely return if the current path only partially matches the extracted path. The error appears to be occurring in Util::create_offline_path function in class-ss-util.php.

Example:
The extracted path “http://example.com/product-category/widgets/“
on a page with the path “http://example.com/product/widget-100/“

will result in the relative path “./../-category/widgets/“
instead of “./../../product-category/widgets/“

Changing the comparison “strpos( $extracted_path, $page_path ) === 0”
To “strpos( $extracted_path, $page_path . ‘/’ ) === 0” appear to fix the above case but probably is not the best solution.

**Comment by patrickposner** [comment]
@sr293 fixed now (and will be included in the next update).

Instead of hardcoding the "/" I opted for wrapping the $page_path variable inside [trailingslashit()](https://developer.wordpress.org/reference/functions/trailingslashit/).

This way it also works if the path already contains a "/" and no duplicates are added.
