### ISSUE TITLE
WP-CLI plugin checksum verification problem

### ISSUE THREAD

**Issue by mraszplewicz** [Simply-Static/simply-static#248]
I am installing the simply-static plugin with WP-CLI:
```
wp plugin install simply-static --version=3.1.8.1 --force --activate
```
then I am trying to verify the checksum with:
```
wp plugin verify-checksums simply-static --version=3.1.8.1
```
and it fails with:
```
+---------------+-------------+-----------------+
| plugin_name   | file        | message         |
+---------------+-------------+-----------------+
| simply-static | security.md | File is missing |
+---------------+-------------+-----------------+
Error: No plugins verified (1 failed).
```

I am not sure if it is a problem with simply-static or with WP-CLI, I've found this issue that seems to be related: https://github.com/wp-cli/checksum-command/issues/46

**Comment by patrickposner** [comment]
@mraszplewicz good catch!

I pushed the fix now, so this issue should be fixed with the next release.

We kept the security.md file only on w.org as it points to the VPD program for w.org submitted security issues.
Now, it's also included in our repository (and in all future releases), so the checksum verification will work.
