### ISSUE TITLE
why delete issue instead of close?

### ISSUE THREAD

**Issue by nadirvishun** [Simply-Static/simply-static#267]
A few days ago I mentioned an issue about generation static `sitemap.xml` and `sitemap_index.xml` content being empty when use `yoast` , but today when I wanted to check it I found that it's gone.
 why delete this issue instead of closing it or stating the reason for it, that's also too unkind to the person who create the issue, isn't it?

**Comment by patrickposner** [comment]
Hey @nadirvishun,

We are deleting issues that aren't bugs in SS but rather generic support requests specific to a certain website.

I don't want to sound mean, but people are constantly creating issues here related to a specific website rather than reporting issues (and providing fixes) to our core software.

Closing them would make it almost impossible for us to search the archive, as they would still be included in the results, and we wouldn't have a way to exclude them.

**Comment by nadirvishun** [comment]
@patrickposner
My feedback is not site-specific, the yoast integration is a feature that comes with your product, but when I use it, I find that the content of the `sitmap.xml` produced by the static is empty, and I'd like to ask for help, isn't that a normal problem with reacting to a product?

**Comment by nadirvishun** [comment]
Now `Simply Static 3.2.4.1` and `Yoast SEO 23.8` environments can generate `sitmap.xml` file properly!
